services:
  user-db:
    image: postgres:15
    container_name: user-postgres
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "${USER_DB_PORT_EXTERNAL}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local_market_net

  redis:
    image: redis:7
    container_name: user-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT_EXTERNAL}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local_market_net

  keycloak-postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local_market_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "${KC_PORT_EXTERNAL}:8080"
    networks:
      - local_market_net

  user-service:
    build: .
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT_EXTERNAL}:${USER_SERVICE_PORT_INTERNAL}"
    environment:
      SPRING_PROFILES_ACTIVE: ${USER_SERVICE_PROFILE}
      DB_URL: jdbc:postgresql://user-db:5432/${USER_DB_NAME}
      DB_USERNAME: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASE: 0
      SERVER_PORT: ${USER_SERVICE_PORT_INTERNAL}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/${KC_REALM_NAME}
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - local_market_net

volumes:
  pgdata:
  keycloak_pgdata:

networks:
  local_market_net:
    external: true