spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}
