apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/volumes/user_db_volume