apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config-map
data:
  SPRING_PROFILES_ACTIVE: k8s
  DB_URL: jdbc:postgresql://user-db:5432/user_service
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8081/realms/online-market/protocol/openid-connect/certs
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth.market.local/realms/online-market
  SAMPLING_PROBABILITY: "1.0"
  TEMPO_URL: http://tempo:4318/v1/traces