apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: keycloak-pv
  resources:
    requests:
      storage: 256Mi