apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/volumes/auth_db_volume