apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-postgres
  name: keycloak-postgres
spec:
  selector:
    app: keycloak-postgres
  ports:
    - name: tcp-5432
      port: 5432
      targetPort: 5432