apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak-postgres
  name: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: keycloak-postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: auth-db-secret
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-pgdata
      restartPolicy: Always
      volumes:
        - name: keycloak-pgdata
          persistentVolumeClaim:
            claimName: keycloak-pvc